title: Cancer Cell Line Drug Resistance Analysis
description: Final academic project for Advanced Diploma in Biotechnology – Transcriptomic analysis of drug-resistant breast cancer cell lines.
theme: jekyll-theme-cayman
markdown: kramdown
